spring:
  profiles:
    active: test
server:
  port: 9090
---
spring:
  profiles: test
  application:
    name: test-config-server
---
spring:
  profiles: prod
  application:
    name: prod-config-server